In [114]:
import pandas as pd
import sqlite3
import logging

In [115]:
# Set up logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

In [116]:
def extract(file_path):
    logging.info("Starting data extraction")
    try:
        df = pd.read_csv(file_path)
        logging.info(f"Data extracted successfully: {df.shape[0]} rows, {df.shape[1]} columns")
        return df
    except Exception as e:
        logging.error(f"Error during extraction: {e}")
        raise

In [117]:
def transform(df):
    logging.info("Starting data transformation")

    # Rename columns
    df = df.rename(columns={
        'Order.Date': 'order_date',
        'Order.ID': 'order_id',
        'Product.ID': 'product_id',
        'Product.Name': 'product_name',
        'Profit': 'profit',
        'Sales': 'sales'
    })

    # Convert order_date to datetime
    df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

    # Data quality check: report missing values
    missing_values = df.isnull().sum()
    logging.info(f"Missing values before handling:\n{missing_values}")

    # Handle missing profit or sales by dropping these rows (or fill if preferred)
    df = df.dropna(subset=['profit', 'sales', 'order_date'])

    # Create profit_margin column
    df['profit_margin'] = df['profit'] / df['sales']

    logging.info("Transformation complete")
    return df

In [118]:

def load(df, db_name, table_name='sales'):
    logging.info("Starting data load")
    try:
        conn = sqlite3.connect(db_name)
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        logging.info(f"Data loaded successfully into {table_name} table in {db_name}")
        return conn
    except Exception as e:
        logging.error(f"Error during load: {e}")
        raise

def verify(conn, query):
    logging.info(f"Running query for verification:\n{query}")
    result = pd.read_sql_query(query, conn)
    print(result)

In [119]:
if __name__ == '__main__':
    file_path = 'superstore.csv'
    db_name = 'superstore_sales.db'

In [121]:
 df = extract(file_path)

INFO: Starting data extraction
INFO: Data extracted successfully: 51290 rows, 27 columns

In [122]:
df_clean

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,order_date,order_id,...,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum,profit_margin
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2,0.491116
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4,0.489095
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32,0.468657
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32,0.479827
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40,0.518400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,Corporate,2014-12-04 00:00:00.000,Same Day,5.15,California,Binders,2014,North America,49,0.327148
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,Corporate,2014-12-04 00:00:00.000,Same Day,0.44,California,Binders,2014,North America,49,0.350933
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,Home Office,2014-12-21 00:00:00.000,First Class,0.31,California,Binders,2014,North America,51,0.356700
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,Home Office,2014-12-26 00:00:00.000,First Class,15.95,California,Binders,2014,North America,52,0.377000
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,Corporate,2014-12-30 00:00:00.000,Standard Class,9.59,California,Binders,2014,North America,52,0.336518

In [97]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [99]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [100]:
df_clean = transform(df)

INFO: Starting data transformation
INFO: Missing values before handling:
Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
order_date        0
order_id          0
Order.Priority    0
product_id        0
product_name      0
profit            0
Quantity          0
Region            0
Row.ID            0
sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64
INFO: Transformation complete

In [101]:
df

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03 00:00:00.000,CA-2014-109701,...,69,Corporate,2014-12-04 00:00:00.000,Same Day,5.15,California,Binders,2014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03 00:00:00.000,CA-2014-109701,...,9,Corporate,2014-12-04 00:00:00.000,Same Day,0.44,California,Binders,2014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18 00:00:00.000,CA-2014-106964,...,12,Home Office,2014-12-21 00:00:00.000,First Class,0.31,California,Binders,2014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25 00:00:00.000,CA-2014-145219,...,90,Home Office,2014-12-26 00:00:00.000,First Class,15.95,California,Binders,2014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26 00:00:00.000,CA-2014-121398,...,154,Corporate,2014-12-30 00:00:00.000,Standard Class,9.59,California,Binders,2014,North America,52

In [102]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [103]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [104]:
connection = load(df_clean, db_name)

INFO: Starting data load
INFO: Data loaded successfully into sales table in superstore_sales.db

In [105]:
verify(connection, 'SELECT * FROM sales LIMIT 10;')

INFO: Running query for verification:
SELECT * FROM sales LIMIT 10;

          Category         City        Country Customer.ID     Customer.Name  \
0  Office Supplies  Los Angeles  United States   LS-172304  Lycoris Saunders
1  Office Supplies  Los Angeles  United States   MV-174854     Mark Van Huff
2  Office Supplies  Los Angeles  United States   CS-121304      Chad Sievert
3  Office Supplies  Los Angeles  United States   CS-121304      Chad Sievert
4  Office Supplies  Los Angeles  United States   AP-109154    Arthur Prichep
5  Office Supplies  Los Angeles  United States   JF-154904      Jeremy Farry
6  Office Supplies  Los Angeles  United States   WB-218504     William Brown
7  Office Supplies  Los Angeles  United States   JA-159704      Joseph Airdo
8  Office Supplies  Los Angeles  United States   SP-209204      Susan Pistek
9  Office Supplies  Los Angeles  United States   RL-196154         Rob Lucas

   Discount Market  记录数           order_date        order_id  ...   Segment  \
0       0.0     US    1  2011-01-07 00:00:00  CA-2011-130813  ...  Consumer
1       0.0     US    1  2011-01-21 00:00:00  CA-2011-148614  ...  Consumer
2       0.0     US    1  2011-08-05 00:00:00  CA-2011-118962  ...  Consumer
3       0.0     US    1  2011-08-05 00:00:00  CA-2011-118962  ...  Consumer
4       0.0     US    1  2011-09-29 00:00:00  CA-2011-146969  ...  Consumer
5       0.0     US    1  2011-10-19 00:00:00  CA-2011-117317  ...  Consumer
6       0.0     US    1  2011-11-04 00:00:00  CA-2011-125829  ...  Consumer
7       0.0     US    1  2011-11-12 00:00:00  CA-2011-151295  ...  Consumer
8       0.0     US    1  2011-11-22 00:00:00  CA-2011-135090  ...  Consumer
9       0.0     US    1  2011-12-05 00:00:00  CA-2011-133830  ...  Consumer

                 Ship.Date       Ship.Mode  Shipping.Cost       State  \
0  2011-01-09 00:00:00.000    Second Class           4.37  California
1  2011-01-26 00:00:00.000  Standard Class           0.94  California
2  2011-08-09 00:00:00.000  Standard Class           1.81  California
3  2011-08-09 00:00:00.000  Standard Class           4.59  California
4  2011-10-03 00:00:00.000  Standard Class           1.32  California
5  2011-10-19 00:00:00.000        Same Day           2.39  California
6  2011-11-11 00:00:00.000  Standard Class           1.15  California
7  2011-11-16 00:00:00.000  Standard Class           0.92  California
8  2011-11-26 00:00:00.000  Standard Class           6.98  California
9  2011-12-10 00:00:00.000  Standard Class           1.99  California

  Sub.Category  Year        Market2 weeknum profit_margin
0        Paper  2011  North America       2      0.491116
1        Paper  2011  North America       4      0.489095
2        Paper  2011  North America      32      0.468657
3        Paper  2011  North America      32      0.479827
4        Paper  2011  North America      40      0.518400
5        Paper  2011  North America      43      0.506585
6        Paper  2011  North America      45      0.491116
7        Paper  2011  North America      46      0.488367
8        Paper  2011  North America      48      0.448500
9        Paper  2011  North America      50      0.471151

[10 rows x 28 columns]

In [109]:
verify(connection, 'SELECT DISTINCT Country FROM sales;')

INFO: Running query for verification:
SELECT DISTINCT Country FROM sales;

           Country
0    United States
1           France
2          Germany
3      El Salvador
4        Guatemala
..             ...
142       Honduras
143      Argentina
144           Peru
145      Venezuela
146     Tajikistan

[147 rows x 1 columns]

In [110]:
verify(connection, 'SELECT profit_margin, profit, sales FROM sales LIMIT 10;')

INFO: Running query for verification:
SELECT profit_margin, profit, sales FROM sales LIMIT 10;

   profit_margin   profit  sales
0       0.491116   9.3312     19
1       0.489095   9.2928     19
2       0.468657   9.8418     21
3       0.479827  53.2608    111
4       0.518400   3.1104      6
5       0.506585   6.5856     13
6       0.491116   9.3312     19
7       0.488367   5.8604     12
8       0.448500  24.2190     54
9       0.471151  23.0864     49

In [111]:
df

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03 00:00:00.000,CA-2014-109701,...,69,Corporate,2014-12-04 00:00:00.000,Same Day,5.15,California,Binders,2014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03 00:00:00.000,CA-2014-109701,...,9,Corporate,2014-12-04 00:00:00.000,Same Day,0.44,California,Binders,2014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18 00:00:00.000,CA-2014-106964,...,12,Home Office,2014-12-21 00:00:00.000,First Class,0.31,California,Binders,2014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25 00:00:00.000,CA-2014-145219,...,90,Home Office,2014-12-26 00:00:00.000,First Class,15.95,California,Binders,2014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26 00:00:00.000,CA-2014-121398,...,154,Corporate,2014-12-30 00:00:00.000,Standard Class,9.59,California,Binders,2014,North America,52

In [112]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority',
       'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID',
       'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State',
       'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [113]:
df_clean

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,order_date,order_id,...,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum,profit_margin
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,...,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2,0.491116
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,...,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4,0.489095
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32,0.468657
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,...,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32,0.479827
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,...,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40,0.518400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,Corporate,2014-12-04 00:00:00.000,Same Day,5.15,California,Binders,2014,North America,49,0.327148
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-03,CA-2014-109701,...,Corporate,2014-12-04 00:00:00.000,Same Day,0.44,California,Binders,2014,North America,49,0.350933
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-18,CA-2014-106964,...,Home Office,2014-12-21 00:00:00.000,First Class,0.31,California,Binders,2014,North America,51,0.356700
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-25,CA-2014-145219,...,Home Office,2014-12-26 00:00:00.000,First Class,15.95,California,Binders,2014,North America,52,0.377000
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-26,CA-2014-121398,...,Corporate,2014-12-30 00:00:00.000,Standard Class,9.59,California,Binders,2014,North America,52,0.336518